---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vipkub
  namespace: metallb-system
spec:
  addresses:
    - "{{ ip_metallb }}"
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - vipkub

